### ISSUE TITLE
Use tracee to scan external github actions

### ISSUE THREAD

**Issue by javixeneize** [aquasecurity/tracee-action-example#60]
Hi

I am trying to use tracee to scan an external github action, for example, the upload artifact action from github

This is the workflow i have

```
name: Tracee Pipeline Scan
on: [pull_request]

jobs:
  Tracee-Scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@v0.1.0-start

    - name: Store library test results
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: .

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@v0.1.0-stop
      with:
        fail-on-diff: "true"
        create-pr: "true"
```

Would this be a valid use case? This is failing in the stop step, reporting the profile file was not found. However, later in the console it writes it has created a PR, but, nothing has been created

Thanks
